### ISSUE TITLE
FileNotFoundError : Maxscript.api 

### ISSUE THREAD

**Issue by johanboekhoven** [cb109/sublime3dsmax#12] opened 2017-01-04 12:16 UTC
Hey,

I'm getting an error with the autocomplete functionality:

>Traceback (most recent call last):
>  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
>    expr()
>  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 522, in <lambda>
>    run_callback('on_activated', callback, lambda: callback.on_activated(v))
>  File "sublime3dsmax in C:\Users\Jhn\AppData\Roaming\Sublime Text 3\Installed Packages\Send to 3ds Max.sublime-package", line 295, in on_activated
>FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Jhn\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\Send to 3ds Max.sublime-package\\maxscript.api'

I uninstalled and reinstalled the package, but same error occurs. Obviously the files are all there, the package has the maxscript.api file too. So not sure what happens..

Sublime Text 3, Build 3126, 64 bit

If I can do anything let me know!
-Johan

**Comment by cb109** [comment] 2017-01-04 12:55
Hey Johan, thanks for reporting, I can replicate that issue. It probably has problems looking into the `.sublime-package` file which is is a zip. Of course that did not occur when testing locally in my expanded directory :flushed: 

Possibly in `sublime3dsmax.py` line 295 and 300 it needs to handle both a usual filesystem and being inside a zip file when trying to read the api file.

**Comment by johanboekhoven** [comment] 2017-01-04 14:02
That makes sense, though I havent looked at the code myself. A temporary fix would be to unzip the package to a folder with that name, right?

**Comment by cb109** [comment] 2017-01-04 14:10
Yes that should work, unzip and remove the zip afterwards.

**Comment by cb109** [comment] 2017-01-08 15:12
Hi Johan, this should fix it: https://github.com/cb109/sublime3dsmax/pull/13/files
You could do me a favor and give it a quick test: 
1. Make sure the package is installed as usual via package manager.
2. Download the `sublime3dsmax.py` from the pull request above (View > Raw).
3. Close Sublime.
4. Open the `Installed Packages\Send to 3ds Max.sublime-package`
5. Replace the `sublime3dsmax.py` in the package with the one you downloaded.

Then restart Sublime, API completion should now work. A good test is e.g. `polyOps.` and then pressing Ctrl + Space to trigger autocompletion.

Cheers

**Comment by johanboekhoven** [comment] 2017-01-10 08:41
Hey Christoph,

Yes that works great now!
I think that issue is solved then, thanks!

-Johan

**Comment by cb109** [comment] 2017-01-10 20:15
Great, thanks!

**Comment by ross-g** [comment] 2017-05-23 13:18
I came here to report this same problem as it is affecting me at work.

If the issue is known to be fixed now, can the branch be merged into master so that the fix is deployed please? :)
Thanks.

**Comment by cb109** [comment] 2017-05-23 13:30
@ross-g Ah I forgot about this, will try and release this tonight!

**Comment by ross-g** [comment] 2017-05-23 15:21
Thanks, I appreciate it!

**Comment by cb109** [comment] 2017-05-23 20:28
@ross-g Ok `0.9.8` is out, package-control will take a while to pick it up. I am not sure if the auto-update actually works, could you launch sublime tomorrow and tell me if your `sublime3dsmax` updates itself and displays a message including the `0.9.8` changelog? Thanks!

**Comment by ross-g** [comment] 2017-05-24 09:04
@cb109 Thanks. I can confirm that the `sublime3dsmax` package updates to `0.9.8` today, although package control does not show me the changelog after updating the package. But checking Sublimes console shows the update was successful.

**Comment by cb109** [comment] 2017-05-24 09:18
Hm ok, at least it updated, that's the important thing. Maybe I can ditch the `messages` directory, it's a pain to maintain anyway :wink: Thanks for the feedback.

**Closed as completed by cb109** 2017-05-24 09:18 UTC
Labels: bug
